emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    openapi-versions: ["3.1.0"]
    file-type: "json"
    output-file: "openapi.json"
    new-line: "lf"
    omit-unreachable-types: true
